language: go
go:
    - 1.1.1
    - tip
install:
    - go get -u github.com/cznic/fileutil
    - cd /home/travis/gopath/src/github.com/cznic/fileutil && git checkout -f master && git remote add upstream https://github.com/cznic/fileutil && git pull
    - go get github.com/cznic/kv
